### ISSUE TITLE
ResqueCleaner#requeue not working

### ISSUE THREAD

**Issue by bvicenzo** [ono/resque-cleaner#35] opened 2015-10-23 19:40 UTC
Hi guys.

When I try to requeue a job from the console as the readme example says:
```rb
cleaner = Resque::Plugins::ResqueCleaner.new
cleaner.requeue {|j| j["payload"]["args"].size > 0}
```
I'm getting the same error that @devnut described here: https://github.com/resque/resque-loner/issues/49

However, when I run it from the resque-web interface, it works.

Do you have any idea why this behavior?

Thanks.

**Comment by ono** [comment] 2015-11-17 22:49
could you create an example repo that can reproduce the issue?

**Comment by ono** [comment] 2016-09-11 11:40
Closing the issue since the requested information was not provided. Feel free to reopen with a sample app that allows me to reproduce the issue.

**Closed** 2016-09-11 11:40 UTC
